import { QueryProvider } from '@/_context'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body className="h-screen desktop:w-[360px] desktop:mx-auto">
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  )
}
