export { default as Cancel } from './cancel.svg'
export { default as ViewCalendarBtn} from './addEventBtn.svg'
export { default as KakaoIcon } from './kakao.svg'
export { default as DownArrow } from './downarrow.svg'
export { default as UpArrow } from './uparrow.svg'
export { default as Pin } from './pin.svg'
export { default as Trashcan } from './trashcan.svg'
export { default as Rectangle } from './rectangle.svg'
export { default as Plus } from './plus.svg'
export { default as DeleteUser } from './deleteuser.svg'

